### ISSUE TITLE
Create Autonomous Execution Structure

### ISSUE THREAD

**Issue by Koltara** [Team7769/2024-Season#10]
Create an execution structure to build autonomous modes. An abstract class should be created for Autonomous modes that contains the methods that will need to be executed. 

At minimum, the base AutonomousMode class should have the following methods:
1. execute()
2. initialize()
3. abort()
4. isComplete()

The base execution structure should look something like this:
Select Mode -> (Autonomous Init) mode.initialize() -> (Periodic) mode.execute() -> (Periodic) mode.isComplete()

The simplest way to handle the step structure of autonomous would be something like this:
![image](https://github.com/Team7769/2024-Season/assets/6282577/b2398214-69f5-4b65-b942-2c0cee8d4088)

A dropdown selector should be added to the SmartDashboard data that can be used to select an autonomous mode. Finally, a sample Autonomous mode should be created that can execute an autonomous routine. This Autonomous Mode should be able to be selected from the Dashboard and executed when run in autonomous mode.

Acceptance Criteria:
1. The abstract base class exists for creating Autonomous modes.
2. The base class has the methods outlined above
3. A sample Autonomous mode exists that will execute the methods
4. The sample Autonomous mode can be selected and run from the driver station in Autonomous mode.

**Comment by zeep54** [comment]
I'll help. The lights thing is easy I think.
